#!/bin/bash
# Skripti nimi: info.sh
# Kirjeldus: See skript tervitab sisselogitud kasutajat ja väljastab hetkelise kuupäeva ja kellaaja.
# Tervitab sisselogitud kasutajat

echo "Tere, $(whoami)!"

# Kuvab kuupäeva ja kellaaja kujul "Täna on 25.09.2024 kell 9:15"
echo "Täna on $(date '+%d.%m.%Y') kell $(date '+%H:%M')"
