#!/bin/bash
# Skripti eesmärk: Arvutada, mitu bussi täitub täielikult ja mitu inimest jääb üle

# Küsime kasutajalt reisijate arvu
echo -n "Sisesta reisijate arv grupis: "
read reisijad

# Küsime kasutajalt kohtade arvu ühes bussis
echo -n "Sisesta kohtade arv ühes bussis: "
read kohad

# Arvutame täielikult täidetud busside arvu
taidetud_bussid=$(($reisijad / $kohad))

# Arvutame maha jäänud reisijate arvu
maha_jaanud=$(($reisijad % $kohad))

# Väljastame tulemuse
echo "Täidetud busse on: $taidetud_bussid"
echo "Maha jäänud inimesi on: $maha_jaanud"
