#!/bin/bash
# See skript kontrollib, kas kasutaja sisestatud täisarv on paaris või paaritu

# Küsime kasutajalt täisarvu
echo -n "Sisesta suvaline täisarv: "
read arv

# Kontrollime, kas arv on paaris
if [ $((arv % 2)) -eq 0 ]; then
    echo "Antud arv on paaris"
else
    echo "Antud arv on paaritu"
fi
